#!/bin/sh

# this pre-commit hook avoids leaving the repo in a broken state.

echo "Running cargo fmt..."
cargo fmt --all -- --check || exit 1


echo "Running cargo clippy..."
cargo clippy --all-targets --all-features -- -D warnings || exit 1


echo "Running cargo check..."
cargo check || exit 1

echo "All pre-commit checks passed!"
