name: Setup
description: Setup environment for CI

inputs:
  targets:
    description: Comma-separated list of target triples to install for this toolchain
    required: false
  components:
    description: Comma-separated list of components to be additionally installed
    required: false

runs:
  using: 'composite'
  steps:
    - name: Free up disk space
      shell: bash
      run: ${{ github.action_path }}/free_disk_space.sh
    - shell: bash
      run: |
        echo $HOME
        echo ${{ runner.os }}

    - name: Install protoc
      uses: arduino/setup-protoc@v3
      with:
        version: "27.1"

    - uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        targets: ${{ inputs.targets }}
        components: ${{ inputs.components }}

    - uses: Swatinem/rust-cache@v2
      with:
        key: ${{ runner.os }}-${{ inputs.targets }}-rust-cache
        prefix-key: v1-rust
