name: Setup
description: Setup environment for CI

inputs:
  targets:
    description: Comma-separated list of target triples to install for this toolchain
    required: false
  components:
    description: Comma-separated list of components to be additionally installed
    required: false

runs:
  using: 'composite'
  steps:
    - shell: bash
      run: |
        echo $HOME
        echo ${{ runner.os }}

    - uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        targets: ${{ inputs.targets }}
        components: ${{ inputs.components }}

    - uses: Swatinem/rust-cache@v2
      with:
        key: ${{ runner.os }}-${{ inputs.targets }}-rust-cache
