name: Setup
description: Setup environment for CI

inputs:
  targets:
    description: Comma-separated list of target triples to install for this toolchain
    required: false
  components:
    description: Comma-separated list of components to be additionally installed
    required: false

runs:
  using: 'composite'
  steps:
    - name: Free up disk space
      shell: bash
      run: |
        # Source: https://github.com/apache/flink/blob/02d30ace69dc18555a5085eccf70ee884e73a16e/tools/azure-pipelines/free_disk_space.sh
        echo "=============================================================================="
        echo "Freeing up disk space on CI system"
        echo "=============================================================================="
        echo "Listing 100 largest packages"
        dpkg-query -Wf '${Installed-Size}\t${Package}\n' | sort -n | tail -n 100
        df -h
        echo "Removing large packages"
        sudo apt-get remove -y '^ghc-8.*'
        sudo apt-get remove -y '^dotnet-.*'
        sudo apt-get remove -y '^llvm-.*'
        sudo apt-get remove -y 'php.*'
        sudo apt-get remove -y azure-cli google-cloud-sdk hhvm google-chrome-stable firefox powershell mono-devel
        sudo apt-get autoremove -y
        sudo apt-get clean
        df -h
        echo "Removing large directories"
        # deleting 15GB
        rm -rf /usr/share/dotnet/
        df -h
    - shell: bash
      run: |
        echo $HOME
        echo ${{ runner.os }}

    - uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        targets: ${{ inputs.targets }}
        components: ${{ inputs.components }}

    - uses: Swatinem/rust-cache@v2
      with:
        key: ${{ runner.os }}-${{ inputs.targets }}-rust-cache
