disallowed-types = [
  { path = "std::collections::HashMap", reason = "Use hashbrown::HashMap (or datafusion_common::HashMap) for better performance" },
  { path = "std::collections::HashSet", reason = "Use hashbrown::HashSet (or datafusion_common::HashSet) for better performance" },
]

disallowed-methods = [
    { path = "tokio::spawn", reason = "use datafusion::common::runtime::SpawnTask instead to correctly propagate task context" },
]