[package]
name = "datafusion-distributed-ffi-test"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
name = "datafusion_distributed_ffi_test"
crate-type = ["cdylib", "rlib"]

[dependencies]
async-trait = "0.1.89"
datafusion = { workspace = true, default-features = false, features = ["sql"] }
datafusion-ffi = { workspace = true }
datafusion-proto = { workspace = true }
datafusion-functions-aggregate = { workspace = true }
datafusion-functions-window = { workspace = true }
datafusion-python-util = { workspace = true }
pyo3 = { version = "0.28", features = ["extension-module", "abi3", "abi3-py310"] }
pyo3-log = "0.13.3"

[build-dependencies]
pyo3-build-config = "0.28"
